### ISSUE TITLE
Using the `calcjob gotocomputer` command on a non-reachable PK emits critical error

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#186]
I just tried to use the `calcjob gotocomputer` command on an "old" PK, and encountered this error:

```
$ verdi calcjob gotocomputer 1981
Critical: Traceback (most recent call last):
  File "/home/max/codes/aiida-core/aiida/orm/implementation/django/authinfos.py", line 155, in get
    authinfo = DbAuthInfo.objects.get(dbcomputer=computer.id, aiidauser=user.id)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
aiida.backends.djsite.db.models.DoesNotExist: DbAuthInfo matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/codes/aiida-core/aiida/cmdline/commands/cmd_calcjob.py", line 42, in calcjob_gotocomputer
    transport = calcjob.get_transport()
  File "/home/max/codes/aiida-core/aiida/orm/nodes/process/calculation/calcjob.py", line 506, in get_transport
    return self.get_authinfo().get_transport()
  File "/home/max/codes/aiida-core/aiida/orm/nodes/process/calculation/calcjob.py", line 499, in get_authinfo
    return AuthInfo.from_backend_entity(self.backend.authinfos.get(computer=computer, user=self.user))
  File "/home/max/codes/aiida-core/aiida/orm/implementation/django/authinfos.py", line 158, in get
    'User<{}> has no configuration for Computer<{}>'.format(user.email, computer.name)
aiida.common.exceptions.NotExistent: User<nicolas.mounet@epfl.ch> has no configuration for Computer<daint>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/.virtualenvs/aiida/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/max/codes/aiida-core/aiida/cmdline/commands/cmd_calcjob.py", line 44, in calcjob_gotocomputer
    echo.echo_critical(exception)
  File "/home/max/codes/aiida-core/aiida/cmdline/utils/echo.py", line 115, in echo_critical
    click.secho(message, bold=bold, nl=nl, err=err)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/termui.py", line 477, in secho
    message = style(message, **styles)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/termui.py", line 449, in style
    return ''.join(bits)
TypeError: sequence item 1: expected str instance, NotExistent found
```

**Comment by sphuber** [comment]
This is a bug in `aiida-core`. I will open an issue there.

**Comment by chrisjsewell** [comment]
aida-core issue now closed
